from tkinter import *
janela = Tk()
def selecao():
    etq1['text'] ='Local é ' + lista.get(ANCHOR)
janela.title('Atividade')
janela.iconbitmap('kk.ico')
janela.geometry('500x400+150+100')
lbl1 = Label(janela, text='Qual o seu Nome?')
lbl1.pack()
en1 = Entry(janela)
en1.pack()
lbl2 = Label(janela, text='Qual o Sexo?')
lbl2.pack()
var = IntVar()
rb1 = Radiobutton(janela, text='Masculino', variable=var, value=1, fg='Blue')
rb1.pack()
rb2 = Radiobutton(janela, text='Feminino', variable=var, value=2, fg='Magenta')
rb2.pack()
etq2 = Label(janela, text="Qual Estado você mora?")
etq2.pack()
#ScrollBar
frame = Frame(janela)
scrollbar = Scrollbar(frame, orient=VERTICAL)
lista=Listbox(frame,width=20, height=5, yscrollcommand=scrollbar.set)
scrollbar.config(command= lista.yview)
scrollbar.pack(side=RIGHT, fill=Y)
frame.pack()
lista.pack()
minhalista = ['São Paulo', 'Rio de Janeiro', 'Minas Gerais', 'Alagoas', "Amazonas", "Roraima", 'Acre']
for item in minhalista:
    lista.insert(END, item)
janela.geometry('500x400+50+20')
btn1 = Button(janela, text='Selecionado', command=selecao)
btn1.pack()
etq1 = Label(janela, text='')
etq1.pack()
etq3 = Label(janela, text='Qual curso você deseja?').pack()
var1 = IntVar()
Checkbutton(janela, text="Python", variable=var1).pack()
var2= IntVar()
Checkbutton(janela, text="Java", variable=var2).pack()
var3= IntVar()
Checkbutton(janela, text="Java", variable=var3).pack()
janela.mainloop()