from tkinter import *
janela = Tk()
def click1():
    X = int(entrada1.get())
    Y = int(entrada1.get())
    soma = X +  Y 
    etiqueta3 = Label(janela, text=f"{soma}", font=20).pack()
janela.iconbitmap("kk.ico")
janela.title("Pedido Professor")
janela.geometry("500x400+50+20")
etiqueta=Label(janela, text="Calculadora", font=80)
etiqueta.pack()
botao = Button(janela, text="Clique Aqui Para Sair", padx=10, pady=5, bg="Gray", fg="Black", command= janela.quit)
botao.pack()
etiqueta1 = Label(janela, text="Primerio Número: ")
etiqueta1.pack()
entrada1 = Entry(janela, width=20)
entrada1.get()
entrada1.pack()
etiqueta2 = Label(janela, text="Segundo Número: ")
etiqueta2.pack()
entrada2 = Entry(janela, width=20)
entrada2.get()
entrada2.pack()
btn = Button(janela, text="Soma", command=click1 )
btn.pack()
janela.mainloop()